---
title: "Coursework assignment A - 2022-2023"
subtitle: "CS4125 Seminar Research Methodology for Data Science"
author: "Student names"
date: "16/04/2023"
output:
   pdf_document:
      fig_caption: true
      number_sections: true 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\tableofcontents

# Loading data
```{r load data}
setwd("/Users/suhaibbasir/Documents/CS/MSc/SRDS/SeminarDataScience/Assignment_2")
d <- read.csv("data.csv")
```


```{r load, include=FALSE}
# convert the model column to a factor as it is a categorical variable
d$model <- factor(d$model)
# convert the TeD column to a factor as it is a categorical variable
d$TeD <- factor(d$TeD)

# show the first 6 rows of the data
str(d)
```


```{r load libraries, include=FALSE}
d$model_type <- ifelse(d$model %in% c("B1", "B2", "B3"), "Baseline", "Transfer_Learning")
d$num_parts_refined <- ifelse(d$model == "MF", 4,
                          ifelse(d$model == "MS", 1,
                           ifelse(d$model == "MN", 0,
                          ifelse(grepl("^M[1-8]$", d$model), as.numeric(substr(d$model, 2, 2)), 0))))

# print all lines where model = MF
str(d)
```

```{r, include=FALSE}
model <- lm(score ~ model + model_type + TeD + num_parts_refined + Sum + (TrD1 + TrD2 + TrD3 + TrD4 + TrD5 + TrD6 + TrD7 + TrD8) , data = d)
anova_result <- anova(model)
print(anova_result)
summary(model)
```

```{r, include=FALSE}
# str(d)
# table(d$model, d$TeD)

# t test between B1, B2, and B3 vs the rest
d_B <- subset(d, model=="B1" | model=="B2" | model=="B3")
d_M <- subset(d, model=="M1" | model=="M2" | model=="M3" | model=="MF" | model=="MN" | model=="MS")
t.test(d_B$score, d_M$score)

# average for each model
aggregate(score ~ model, data = d, mean)
m <- lm(score~model, d)
summary(m)
AIC(m)

m1 <- lm(score~model+TeD, d)
summary(m1)
AIC(m1)

# compare m and m1
anova(m, m1)
```

# Research question 1
```{r}
m <- lm(score~model, d)
summary(m)
AIC(m)

library(dplyr)
d |> count(TeD, model)

# get count for number of rows with model B1 B2 and B3 and the Ms
```

### Data visualisation
```{r rq one plot}
# plot the average score for each model
library(ggplot2)
ggplot(d, aes(x=model, y=score)) + geom_boxplot() + geom_jitter(width=0.2)

# plot distribution of scores for each model as histogram
ggplot(d, aes(x=score, fill=model)) + geom_histogram(alpha=0.5, position="identity")
ggplot(d, aes(x=score, fill=model)) + geom_density(alpha=0.5)

# transform data to assume normality
d$score_log <- log(d$score)
ggplot(d, aes(x=score_log, fill=model)) + geom_density(alpha=0.5, position="identity")


```

### Estimated marginal means
```{r rq one emmeans}
# install.packages("emmeans")
library(emmeans)
m <- lm(score~model, d)
m1 <- lm(score~model+TeD, d)
m2 <- lm(score~model*TeD, d)
as.data.frame(ref_grid(m))
as.data.frame(ref_grid(m1))
as.data.frame(ref_grid(m2))

# m <- lm(score~model * (Tr1 + Tr2), d)
as.data.frame(ref_grid(m))
emmeans(m, ~model)
pairs(emmeans(m, ~model))

# # get average predicted score for each model from x1
# avg_predictions <- aggregate(prediction ~ model, data = x1, mean)
# avg_predictions

# # get all predictions for B1 from x1
# predictions_B1 <- subset(x1, model=="B1")

# # find average of all predictions for B1
# mean(predictions_B1$prediction)

# pairs(em)
```

# Research question 2

### Data visualisation

```{r}
d$number_of_training_datasets <- rowSums(d[,c("TrD1", "TrD2", "TrD3", "TrD4", "TrD5", "TrD6", "TrD7", "TrD8")])
model <- lm(score ~ model_type * model * TeD + number_of_training_datasets, data = d)
anova_result <- anova(model)
print(anova_result)
```

```{r}
head(d)
model <- lm(score ~ TeD + model + number_of_training_datasets , data = d)
anova_result <- anova(model)
print(anova_result)
```

```{r}
d$num_training_datasets <- rowSums(d[, c("TrD1", "TrD2", "TrD3", "TrD4", "TrD5", "TrD6", "TrD7", "TrD8")])
d$num_training_datasets_1 <- as.factor(d$num_training_datasets)
d$model <- as.factor(d$model)
d$TeD <- as.factor(d$TeD)
modewl <- lm(score ~ (TrD1 + TrD2 + TrD3 + TrD4 + TrD5 + TrD6 + TrD7 + TrD8) * TeD * model * Sum, data = d)
anova_result <- anova(modewl)
print(anova_result)
summary(modewl)
```

```{r}
# Install and load the necessary package
library(dplyr)

# Load the data
data <- read.csv("data.csv")

# Normalize scores for each test dataset
data <- data %>%
  group_by(TeD) %>%
  mutate(normalized_score = (score - mean(score)) / sd(score))

# View the first few rows with normalized scores
(data[, c("TeD", "score", "normalized_score")])

data$model <- as.factor(data$model)
# data$Sum <- as.factor(data$Sum)
modewl <- lm(normalized_score ~ (TrD1 + TrD2 + TrD3 + TrD4 + TrD5 + TrD6 + TrD7 + TrD8) * model * Sum, data = data)

anova_result <- anova(modewl)
print(anova_result)

summary(modewl)
```