---
title: "Coursework assignment A - 2022-2023"
subtitle: "CS4125 Seminar Research Methodology for Data Science"
author: "Student names"
date: "16/04/2023"
output:
   pdf_document:
      fig_caption: true
      number_sections: true 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


\tableofcontents

# Loading data
```{r load data}
setwd("C:/Users/ottev/TU Delft/Year4/Quarter4/CDA/SeminarDataScience/Assignment_2")
d <- read.csv("data.csv")
```


```{r load}
# convert the model column to a factor as it is a categorical variable
d$model <- factor(d$model)
# convert the TeD column to a factor as it is a categorical variable
d$TeD <- factor(d$TeD)
```


```{r load libraries}
# Create variables model type and parts refined
d$model_type <- ifelse(d$model %in% c("B1", "B2", "B3"), "Baseline", "Transfer_Learning")
d$num_parts_refined <- ifelse(d$model == "MF", 4,
                          ifelse(d$model == "MS", 1,
                           ifelse(d$model == "MN", 0,
                          ifelse(grepl("^M[1-8]$", d$model), as.numeric(substr(d$model, 2, 2)), 0))))
```

```{r}
# Anova with all parts
model <- lm(score ~ model + model_type + TeD + num_parts_refined + (TrD1 + TrD2 + TrD3 + TrD4 + TrD5 + TrD6 + TrD7 + TrD8) + Sum , data = d)
anova_result <- anova(model)
print(anova_result)
```

```{r, include=FALSE}
library(dplyr)
```
```{r}
# Normalize scores for each test dataset
d <- d %>%
  group_by(TeD) %>%
  mutate(score = (score - mean(score)) / sd(score))

# Anova with all parts
model <- lm(score ~ model * TeD * (TrD1 + TrD2 + TrD3 + TrD4 + TrD5 + TrD6 + TrD7 + TrD8) , data = d)
anova_result <- anova(model)
print(anova_result)
summary(model)

# # t test between B1, B2, and B3 vs the rest
# d_B <- subset(d, model=="B1" | model=="B2" | model=="B3")
# d_M <- subset(d, model=="M1" | model=="M2" | model=="M3" | model=="MF" | model=="MN" | model=="MS")



# # average for each model
# aggregate(score ~ model, data = d, mean)
# m <- lm(score~model, d)
# summary(m)
# AIC(m)

# m1 <- lm(score~model+TeD, d)
# summary(m1)
# AIC(m1)

# # compare m and m1
# anova(m, m1)
```

